name: Builds, tests & co

on:
  - push
  - pull_request
  - workflow_dispatch

permissions: write-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 4.07.0
          opam-pin: false

      - run: |
          sudo apt install python3-pip
          pip3 install evdev
          
      - run: |
          opam install dune core lwt re color sexp_pretty uutf lwt_ppx uuseg notty async

      - run: opam exec -- dune build
      -  env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
          ls _build/default/bin
          tar -cvf build.tar _build
          gh release upload out build.tar
